apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: default
      containers:
        - name: api-gateway
          image: microservices_demo/api-gateway
          imagePullPolicy: Never # for local images
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: CART_SERVICE_ADDR
              value: 'cart-service:8080'
            - name: CHECKOUT_SERVICE_ADDR
              value: 'checkout-service:8080'
            - name: CURRENCY_SERVICE_ADDR
              value: 'currency-service:8080'
            - name: PRODUCTS_SERVICE_ADDR
              value: 'products-service:8080'
            - name: SHIPPING_SERVICE_ADDR
              value: 'shipping-service:8080'
