apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  type: ClusterIP
  selector:
    app: currency
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
  labels:
    app: currency
spec:
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      serviceAccountName: default
      containers:
        - name: currency
          image: microservices_demo/currency
          imagePullPolicy: Never # for local images
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 8080
          livenessProbe:
            periodSeconds: 5
            grpc:
              port: 8080
