// Code generated by MockGen. DO NOT EDIT.
// Source: shipping.go

// Package mock_shipping is a generated GoMock package.
package mock_shipping

import (
	reflect "reflect"

	shipping "github.com/Arthur199212/microservices-demo/src/shipping/shipping"
	gomock "github.com/golang/mock/gomock"
)

// MockShippingService is a mock of ShippingService interface.
type MockShippingService struct {
	ctrl     *gomock.Controller
	recorder *MockShippingServiceMockRecorder
}

// MockShippingServiceMockRecorder is the mock recorder for MockShippingService.
type MockShippingServiceMockRecorder struct {
	mock *MockShippingService
}

// NewMockShippingService creates a new mock instance.
func NewMockShippingService(ctrl *gomock.Controller) *MockShippingService {
	mock := &MockShippingService{ctrl: ctrl}
	mock.recorder = &MockShippingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShippingService) EXPECT() *MockShippingServiceMockRecorder {
	return m.recorder
}

// GetQuote mocks base method.
func (m *MockShippingService) GetQuote(address shipping.Address, products []shipping.Product) (shipping.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuote", address, products)
	ret0, _ := ret[0].(shipping.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuote indicates an expected call of GetQuote.
func (mr *MockShippingServiceMockRecorder) GetQuote(address, products interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuote", reflect.TypeOf((*MockShippingService)(nil).GetQuote), address, products)
}

// ShipOrder mocks base method.
func (m *MockShippingService) ShipOrder(address shipping.Address, products []shipping.Product) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShipOrder", address, products)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShipOrder indicates an expected call of ShipOrder.
func (mr *MockShippingServiceMockRecorder) ShipOrder(address, products interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShipOrder", reflect.TypeOf((*MockShippingService)(nil).ShipOrder), address, products)
}
