name: CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**/README.md"

env:
  SERVICES: |
    api_gateway
    cart
    checkout
    currency
    payment
    products
    shipping

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Lint
        timeout-minutes: 5
        run: |
          echo $SERIVCES
          for SERVICE in ${SERVICES[@]}; do
            echo "linting $SERVICE..."
            pushd src/$SERVICE
            make lint
            popd
          done

      - name: Unit tests
        timeout-minutes: 10
        run: |
          for SERVICE in ${SERVICES[@]}; do
            echo "testing $SERVICE..."
            pushd src/$SERVICE
            make test
            popd
          done

      - name: Build
        timeout-minutes: 20
        run: |
          echo "Installing skaffold..."
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

          echo "Run skaffold build"
          skaffold build
